condition

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -9,8 +9,10 @@ workflows:
           groups:
             - firebase_credentials
             - google_play_credentials
+            - condition
           vars:
             PACKAGE_NAME: "io.codemagic.dtrdic7" 
+            THIS_PROFILE_PATH_ON_DISK: testing
           java: 17
 
         triggering:
@@ -26,38 +28,40 @@ workflows:
             include: true
             source: false
         scripts:
-        - name: Decode Google credentials
-          script: | 
-            echo $FIREBASE_SERVICE_ACCOUNT > $GOOGLE_APPLICATION_CREDENTIALS
-        - name: Build the app
-          script: | 
-            echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/local.properties"
-            flutter packages pub get
-            flutter build apk --release
-        - name: Distribute app to firebase with gradle plugin
-          script: | 
-            cd android && ./gradlew appDistributionUploadRelease
-
-        # - name: Set Android SDK location
+        # - name: Decode Google credentials
         #   script: | 
-        #      echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
-
-        # - name: Build Android release
+        #     echo $FIREBASE_SERVICE_ACCOUNT > $GOOGLE_APPLICATION_CREDENTIALS
+        # - name: Build the app
         #   script: | 
-        #     LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
-        #     if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
-        #       # fallback in case no build number was found from Google Play.
-        #       # Alternatively, you can `exit 1` to fail the build
-        #       # BUILD_NUMBER is a Codemagic built-in variable tracking the number
-        #       # of times this workflow has been built
-        #         UPDATED_BUILD_NUMBER=$BUILD_NUMBER
-        #     else
-        #         UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
-        #         [--tracks testingtrack]
-        #     fi
-        #     ./gradlew bundleRelease \
-        #         -PversionCode=$UPDATED_BUILD_NUMBER \
-        #         -PversionName=1.0.$UPDATED_BUILD_NUMBER
+        #     echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/local.properties"
+        #     flutter packages pub get
+        #     flutter build apk --release
+        # - name: Distribute app to firebase with gradle plugin
+        #   script: | 
+        #     cd android && ./gradlew appDistributionUploadRelease
+
+        - name: Set Android SDK location
+          script: | 
+             echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
+
+        - name: Build Android release
+          script: | 
+            LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+            if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
+              # fallback in case no build number was found from Google Play.
+              # Alternatively, you can `exit 1` to fail the build
+              # BUILD_NUMBER is a Codemagic built-in variable tracking the number
+              # of times this workflow has been built
+                UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+            else
+                UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+                [--tracks testingtrack]
+            fi
+            ./gradlew bundleRelease \
+                -PversionCode=$UPDATED_BUILD_NUMBER \
+                -PversionName=1.0.$UPDATED_BUILD_NUMBER
+            $CONDITION
+            
 
         artifacts:
           - app/build/outputs/**/*.aab
@@ -70,9 +74,8 @@ workflows:
               notify:
                 success: true
                 failure: false
-            firebase:
-                firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
-            # google_play:
-            #   credentials: $GOOGLE_APPLICATION_CREDENTIALS
-            #   track: production 
-            #   submit_as_draft: false
+            # firebase:
+            #     firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
+            google_play:
+              credentials: $GOOGLE_APPLICATION_CREDENTIALS
+              track: internal 
