trying powershell script

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -17,12 +17,23 @@ workflows:
             echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
         - name: Build Android release
           script: | 
-            LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
-                UPDATED_BUILD_NUMBER=$BUILD_NUMBER
-            fi
-            cd app
-            ./gradlew bundleRelease \
-                -PversionCode=$UPDATED_BUILD_NUMBER \
+            $PACKAGE_NAME="io.codemagic.dtrdic7"
+            $LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name $PACKAGE_NAME)
+
+            if ([string]::IsNullOrEmpty($LATEST_GOOGLE_PLAY_BUILD_NUMBER)) {
+                # fallback in case no build number was found from Google Play.
+                # Alternatively, you can `exit 1` to fail the build
+                # BUILD_NUMBER is a Codemagic built-in variable tracking the number
+                # of times this workflow has been built
+                $UPDATED_BUILD_NUMBER=$env:BUILD_NUMBER
+            }
+            else {
+                $UPDATED_BUILD_NUMBER=([int]$LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1)
+            }
+
+            cd android
+            .\gradlew bundleRelease `
+                -PversionCode=$UPDATED_BUILD_NUMBER `
                 -PversionName=1.0.$UPDATED_BUILD_NUMBER
         artifacts:
           - app/build/outputs/**/*.aab
