pre-defined-steps

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,4 +1,11 @@
+definitions: 
+  pre-defined-steps: &pre-defined-steps
+    - name: Run analyze
+      script: melos run analyze
+    - name: Run analyze
+      script: melos run analyze
 workflows:
+
     native-android:
         name: Native android
         max_build_duration: 120
@@ -22,29 +29,33 @@ workflows:
           - pattern: "dev"
             include: true
             source: false
-pre-defined-workflows:
-      - workflow: setup
-        arguments:
-          script: |
-            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
-      - workflow: build
-        arguments:
-          script: |
+
+
+        scripts:
+        - name: steps that are repeating
+          <<: *pre-defined-steps
+
+        - name: Set Android SDK location
+          script: | 
+             echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
+
+        - name: Build Android release
+          script: | 
             LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
             if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
               # fallback in case no build number was found from Google Play.
               # Alternatively, you can `exit 1` to fail the build
               # BUILD_NUMBER is a Codemagic built-in variable tracking the number
               # of times this workflow has been built
-              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+                UPDATED_BUILD_NUMBER=$BUILD_NUMBER
             else
-              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
-              [--tracks testingtrack]
+                UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+                [--tracks testingtrack]
             fi
             cd $CM_BUILD_DIR/android
             ./gradlew bundleRelease \
-              -PversionCode=$UPDATED_BUILD_NUMBER \
-              -PversionName=1.0.$UPDATED_BUILD_NUMBER
+                -PversionCode=$UPDATED_BUILD_NUMBER \
+                -PversionName=1.0.$UPDATED_BUILD_NUMBER
         artifacts:
           - app/build/outputs/**/*.aab
           - app/build/outputs/**/*.apk
@@ -61,47 +72,63 @@ pre-defined-workflows:
               track: testingtrack
               submit_as_draft: true
 
-native-android2:
-      name: Native android2
-      max_build_duration: 120
-      instance_type: linux_x2
-      environment:
-        android_signing:
-          - davidKeystore
-        groups:
-          - google_play_credentials 
-        vars:
-          PACKAGE_NAME: "io.codemagic.dtrdic7" 
-        java: 19
-      triggering:
-        events:
-            - pull_request
-            - push
-        branch_patterns:
-        - pattern: "main"
-          include: true
-          source: false
-        - pattern: "dev"
-          include: true
-          source: false
-          steps:
-        - name: Setup
-          workflow: setup  # Calling the 'setup' pre-defined workflow
+  native-android:
+        name: Native android2
+        max_build_duration: 120
+        instance_type: linux_x2
+        environment:
+          android_signing:
+            - davidKeystore
+          groups:
+            - google_play_credentials 
+          vars:
+            PACKAGE_NAME: "io.codemagic.dtrdic7" 
+          java: 19
+        triggering:
+          events:
+              - pull_request
+              - push
+          branch_patterns:
+          - pattern: "main"
+            include: true
+            source: false
+          - pattern: "dev"
+            include: true
+            source: false
+        scripts:
+        - name: Set Android SDK location
+          script: | 
+              echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
 
-        - name: Build
-          workflow: build  # Calling the 'build' pre-defined workflow
-      artifacts:
-        - app/build/outputs/**/*.aab
-        - app/build/outputs/**/*.apk
+        - name: Build Android release
+          script: | 
+            LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+            if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
+              # fallback in case no build number was found from Google Play.
+              # Alternatively, you can `exit 1` to fail the build
+              # BUILD_NUMBER is a Codemagic built-in variable tracking the number
+              # of times this workflow has been built
+                UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+            else
+                UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+                [--tracks testingtrack]
+            fi
+            cd $CM_BUILD_DIR/android
+            ./gradlew bundleRelease \
+                -PversionCode=$UPDATED_BUILD_NUMBER \
+                -PversionName=1.0.$UPDATED_BUILD_NUMBER
+        artifacts:
+          - app/build/outputs/**/*.aab
+          - app/build/outputs/**/*.apk
 
-      publishing: 
-          email:
-            recipients:
-              - david@nevercode.io
-            notify:
-              success: true
-              failure: false
-          google_play:
-            credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
-            track: testingtrack
-            submit_as_draft: true
+        publishing: 
+            email:
+              recipients:
+                - david@nevercode.io
+              notify:
+                success: true
+                failure: false
+            google_play:
+              credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
+              track: testingtrack
+              submit_as_draft: true
