java 19

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -2,7 +2,7 @@ workflows:
     native-android:
         name: Native android
         max_build_duration: 120
-        instance_type: windows_x2
+        instance_type: mac_mini_m1
         environment:
           android_signing:
             - davidKeystore
@@ -10,28 +10,26 @@ workflows:
             - google_play_credentials
           vars:
             PACKAGE_NAME: "io.codemagic.dtrdic7"
-          java: 17
+          java: 19
         scripts:
         - name: Set Android SDK location
           script: | 
              echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
         - name: Build Android release
           script: | 
-            $PACKAGE_NAME="io.codemagic.dtrdic7"
-            $LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name $PACKAGE_NAME)
-
-            if ([string]::IsNullOrEmpty($LATEST_GOOGLE_PLAY_BUILD_NUMBER)) {
-                # fallback in case no build number was found from Google Play.
-                # Alternatively, you can `exit 1` to fail the build
-                # BUILD_NUMBER is a Codemagic built-in variable tracking the number
-                # of times this workflow has been built
-                $UPDATED_BUILD_NUMBER=$env:BUILD_NUMBER
-            }
-            else {
-                $UPDATED_BUILD_NUMBER=([int]$LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1)
-            }
-            .\gradlew bundleRelease `
-                -PversionCode=$UPDATED_BUILD_NUMBER `
+            LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+            if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
+              # fallback in case no build number was found from Google Play.
+              # Alternatively, you can `exit 1` to fail the build
+              # BUILD_NUMBER is a Codemagic built-in variable tracking the number
+              # of times this workflow has been built
+                UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+            else
+                UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+            fi
+            cd android
+            ./gradlew bundleRelease \
+                -PversionCode=$UPDATED_BUILD_NUMBER \
                 -PversionName=1.0.$UPDATED_BUILD_NUMBER
         artifacts:
           - app/build/outputs/**/*.aab
