one step

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -5,28 +5,26 @@ definitions:
   env_versions: &env_versions
     java: 19
   scripts: 
-    - &pre-defined-steps
+    scripts_group: &script_group
       name: Set Android SDK location
       script: | 
           echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
-    - &build-android-release
-      name: Build Android release
-      script: | 
-        LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
-        if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
-          # fallback in case no build number was found from Google Play.
-          # Alternatively, you can `exit 1` to fail the build
-          # BUILD_NUMBER is a Codemagic built-in variable tracking the number
-          # of times this workflow has been built
-            UPDATED_BUILD_NUMBER=$BUILD_NUMBER
-        else
-            UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
-            [--tracks testingtrack]
-        fi
-        cd $CM_BUILD_DIR/android
-        ./gradlew bundleRelease \
-            -PversionCode=$UPDATED_BUILD_NUMBER \
-            -PversionName=1.0.$UPDATED_BUILD_NUMBER
+          echo "Running build steps..."
+          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
+            # fallback in case no build number was found from Google Play.
+            # Alternatively, you can `exit 1` to fail the build
+            # BUILD_NUMBER is a Codemagic built-in variable tracking the number
+            # of times this workflow has been built
+              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+          else
+              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+              [--tracks testingtrack]
+          fi
+          cd $CM_BUILD_DIR/android
+          ./gradlew bundleRelease \
+              -PversionCode=$UPDATED_BUILD_NUMBER \
+              -PversionName=1.0.$UPDATED_BUILD_NUMBER
 
 workflows:
     native-android:
@@ -55,8 +53,7 @@ workflows:
 
 
         scripts:
-        - *pre-defined-steps
-        - *build-android-release
+        - *script_group
 
         artifacts:
           - app/build/outputs/**/*.aab
