revert all

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,31 +1,3 @@
-definitions: 
-  instance_linux_x2: &instance_linux_x2
-    instance_type: linux_x2
-    max_build_duration: 120
-  env_versions: &env_versions
-    java: 19
-  scripts: 
-    scripts_group: &script_group
-      name: Set Android SDK location
-      script: | 
-          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
-          echo "Running build steps..."
-          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
-          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
-            # fallback in case no build number was found from Google Play.
-            # Alternatively, you can `exit 1` to fail the build
-            # BUILD_NUMBER is a Codemagic built-in variable tracking the number
-            # of times this workflow has been built
-              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
-          else
-              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
-              [--tracks testingtrack]
-          fi
-          cd $CM_BUILD_DIR/android
-          ./gradlew bundleRelease \
-              -PversionCode=$UPDATED_BUILD_NUMBER \
-              -PversionName=1.0.$UPDATED_BUILD_NUMBER
-
 workflows:
     native-android:
         name: Native android
@@ -51,10 +23,28 @@ workflows:
             include: true
             source: false
 
-
         scripts:
-        - *script_group
+        - name: Set Android SDK location
+          script: | 
+             echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
 
+        - name: Build Android release
+          script: | 
+            LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+            if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
+              # fallback in case no build number was found from Google Play.
+              # Alternatively, you can `exit 1` to fail the build
+              # BUILD_NUMBER is a Codemagic built-in variable tracking the number
+              # of times this workflow has been built
+                UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+            else
+                UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+                [--tracks testingtrack]
+            fi
+            cd $CM_BUILD_DIR/android
+            ./gradlew bundleRelease \
+                -PversionCode=$UPDATED_BUILD_NUMBER \
+                -PversionName=1.0.$UPDATED_BUILD_NUMBER
         artifacts:
           - app/build/outputs/**/*.aab
           - app/build/outputs/**/*.apk
