google_credentials3

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -8,7 +8,7 @@ workflows:
           - davidKeystore
         groups:
         # - firebase_credentials
-          - google_play_credentials
+          - google_credentials3
           - condition
           - tracks
         vars:
@@ -71,18 +71,17 @@ workflows:
 
       - name: Build Android release
         script: | 
-         UPDATED_BUILD_NUMBER=$BUILD_NUMBER
-          # LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
-          # if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
-          #   # fallback in case no build number was found from Google Play.
-          #   # Alternatively, you can `exit 1` to fail the build
-          #   # BUILD_NUMBER is a Codemagic built-in variable tracking the number
-          #   # of times this workflow has been built
-          #     UPDATED_BUILD_NUMBER=$BUILD_NUMBER
-          # else
-          #     UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
-          #     [--tracks testingtrack]
-          #fi
+          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
+            # fallback in case no build number was found from Google Play.
+            # Alternatively, you can `exit 1` to fail the build
+            # BUILD_NUMBER is a Codemagic built-in variable tracking the number
+            # of times this workflow has been built
+              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+          else
+              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+              [--tracks testingtrack]
+          fi
           ./gradlew bundleRelease \
               -PversionCode=$UPDATED_BUILD_NUMBER \
               -PversionName=1.0.$UPDATED_BUILD_NUMBER 
@@ -100,5 +99,5 @@ workflows:
           # firebase:
           #     firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
           google_play:
-            credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
+            credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS3
             track: testingtrack
